### PR TITLE
Fix #80 Item.getFile()

### LINKED ISSUE #80: Fix nullability issue in Item.getFile() and depending methods
getFile() method converts underlying uri to file, which can fail for non file based items (http). Instead of leaving the isFileBased() check on the user of the API, the method should instead return null if the file is not filebased. This behavior should cascade to other methods in the Item that use this method and consistently return null if the item is not file based.

Note that even if uri.toFileOrNull() would now only be called if the isFileBased() check returns true, tehe uri still can be malformed for some reason, thus the !! operator will remain as is - however it will only take effect for malformed file uris instead of any non file uri as it is now.

### PR DESCRIPTION
**Pull request by sghpjuikit**
non file based items now return null for getFile and related methods

### CODE REVIEW

File: src/sp/it/pl/audio/tagging/Metadata.kt [hunk 1]
```diff
@@ -619,21 +620,18 @@ class Metadata: Item, Serializable {
         null
     }
 
-    private fun readArt(): Artwork? {
-        val af = if (isFileBased()) getFile().readAudioFile().orNull() else null
-        return af?.tag?.firstArtwork
-    }
+    private fun readArt(): Artwork? = getFile()?.let { it.readAudioFile().orNull() }?.tag?.firstArtwork
```
Comment (Xerus2000) [inline src/sp/it/pl/audio/tagging/Metadata.kt]: should this really be named `read` and not `get`?

File: src/sp/it/pl/audio/tagging/Metadata.kt [hunk 2]
```diff
@@ -619,21 +620,18 @@ class Metadata: Item, Serializable {
...
 
     /** @return the cover image file on a file system or null if this item is not file based */
     private fun readCoverOfDir(): Cover? {
```
Comment (Xerus2000) [inline src/sp/it/pl/audio/tagging/Metadata.kt]:
```suggestion
    private fun findDirCover(): Cover? {
```
seems like a more proper name, since it does not simply read but search.

File: src/sp/it/pl/audio/tagging/MetadataReader.java [hunk 3]
```diff
@@ -37,7 +37,7 @@ public static Metadata readMetadata(Item item) {
 		}
 
 		if (item.isFileBased()) {
-			return readAudioFile(item.getFile())
+			return readAudioFile(noNull(item.getFile()))
```
Comment (Xerus2000) [inline src/sp/it/pl/audio/tagging/MetadataReader.java]: You already check whether it isFileBased, so `getFile` doubles it up again. Either create a ``getFileDirect` method, or create some lambda function that checks whether the file isFileBased and executes one of two lambdas depending on the result with the file as parameter.

File: src/sp/it/pl/audio/Item.kt [hunk 4]
```diff
@@ -23,10 +25,9 @@ abstract class Item {
     fun isFileBased(): Boolean = "file"==uri.scheme
 
     /**
-     * @return absolute file this item represents
-     * @throws RuntimeException if this item is not file based
+     * @return absolute file this item represents or null if it is not based on file
      */
-    open fun getFile() = uri.toFileOrNull()!!.absoluteFile!!
+    open fun getFile(): File? = if (isFileBased()) uri.toFileOrNull()!!.absoluteFile else  null
```
[the remark this answers is not in the document]
Comment (sghpjuikit) [reply src/sp/it/pl/audio/Item.kt]: The proposed solution looks nice.

My solution however makes the potential failure explicit, which is a good thing. One thing I learned is that URI.create(), new URI(), new File(), etc are very confusing. These are fairly outdated and there is a bit of inconsistency in when and how they end up throwing. I actually deprecated new File(URI) for this reason. That is why the URI.toFileOrNull() exists - for cases where we do not care about the exception, because we expect it to work every single time. It is exactly the same as String.toIntOrNull methods provided by Kotlin stdlib.

Which is why I prefer my solution, but the consuming of the exception does make me little concerned. One can never be too sure. The file uri in item should always be well formed, but...

I'll think about this a bit.

File: src/sp/it/pl/audio/playlist/PlaylistItem.kt [hunk 5]
```diff
@@ -121,7 +121,7 @@ class PlaylistItem: Item {
 
         if (isFileBased()) {
             throwIfFxThread()
-            getFile().readAudioFile().orNull()?.let { f ->
+            getFile()!!.readAudioFile().orNull()?.let { f ->
```
[the remark this answers is not in the document]
Comment (sghpjuikit) [reply src/sp/it/pl/audio/playlist/PlaylistItem.kt]: You are right to point out the problem and I was hesitant to write it that way, but decided in favor because it is more readable than just checking null - that hides the logic of the decision from the reader and puts the very existence of isFileBased() method to question. Consuming the null from getFile() is fine, but not using it to perform the isFileBased() check - there is a method for that with a clear name and all! This is also premature optimization. The call is non blocking and in order of ns. Consumer of the API also shouldn't know the call is repeated and it may not be in the future.

Once we update Kotlin to 1.3, isFileBased() will receive contract that will specify that if it returns true, getFile() returns non null File. This will remove usages of !! after getFile() after isFileBased() is called.
Check https://proandroiddev.com/kotlin-contracts-make-great-deals-with-the-compiler-f524e57f11c

I believe that once the contract is there, this solution becomes very elegant. What developer wants to do here is to handle filebased and non file based cases differently -split the logic and this solution does exactly that, explicitly.

As for the getFileDirect() method - im absolutely against. It complicates API and involves consumer with implementation details.

File: src/sp/it/pl/audio/tagging/Metadata.kt (hunk 1 above)
Comment (sghpjuikit) [reply src/sp/it/pl/audio/tagging/Metadata.kt]: getX nomenclature is an abomination and should never be used for things that compute, let alone blocking calls. readArt(), computeArt(),obtain, receive, retrieve, etc are all fine. get is not. In Kotlin get() even receives special treatment (can be invoked as []) - it definitely should be used carefully, because get() should be an accessor, not computer.

If you have better name, im open to suggestion, perhaps we can settle on a specific style. But getArt() is a no go.

File: src/sp/it/pl/audio/tagging/Metadata.kt (hunk 2 above)
Comment (sghpjuikit) [reply src/sp/it/pl/audio/tagging/Metadata.kt]: Because the return type is Cover (whether it is loaded Image or not is +- impl detail), Id argue the search is only a part of the logic performed, but I dont mind changing it. Seems reasonable.

Comment (sghpjuikit) [reply src/sp/it/pl/audio/tagging/Metadata.kt]: There is also method called getReadCoverOfTag(), which is a typo. So, I think all three methods should have th esame prefix. if not read, find ?

File: src/sp/it/pl/audio/tagging/MetadataReader.java (hunk 3 above)
Comment (sghpjuikit) [reply src/sp/it/pl/audio/tagging/MetadataReader.java]: Java... Not even going to bother. Will be refactored.

But I have to say:
The proposed lambda is an elegant solution and much more viable than the proposed method, but its still a complication that is not substantiated. I hate to call 'premature optimization', but calling same method twice is not as bad as it sounds - as long as its instantaneous call and we stay in Java-land. I also hate calling the same thing twice, but please bear in mind that isFileBased being called in getFile() is implementation detail that the caller should not be concerned about. Just let the API do its job instead of trying to outsmart it.

Readability beats performance here.

Comment (sghpjuikit) [reply src/sp/it/pl/audio/tagging/MetadataReader.java]: PS: the (noninlined) lambda would probably incur more performance impact than calling isFileBased() twice... Using callbacks to hide internal logic is fine, using it for convenience is questionable practice. API with callbacks are suspicious.

File: src/sp/it/pl/audio/Item.kt (hunk 4 above)
[the remark this answers is not in the document]
Comment (Xerus2000) [reply src/sp/it/pl/audio/Item.kt]: You could create a File.toUrlOrThrow or smth

File: src/sp/it/pl/audio/tagging/MetadataReader.java (hunk 3 above)
Comment (Xerus2000) [reply src/sp/it/pl/audio/tagging/MetadataReader.java]: Of course you'd inline that ^^

File: src/sp/it/pl/audio/Item.kt (hunk 4 above)
[the remark this answers is not in the document]
Comment (sghpjuikit) [reply src/sp/it/pl/audio/Item.kt]: Will be solved in #85. There is more methods affected and thus out of scope of this PR.

**Comment by sghpjuikit** [comment]
Please resolve or comment on the issues.

File: src/sp/it/pl/audio/playlist/PlaylistItem.kt (hunk 5 above)
[the remark this answers is not in the document]
Comment (Xerus2000) [reply src/sp/it/pl/audio/playlist/PlaylistItem.kt]: Kotlin 1.3 is here! Let's go :)

File: src/sp/it/pl/audio/tagging/Metadata.kt (hunk 2 above)
Comment (Xerus2000) [reply src/sp/it/pl/audio/tagging/Metadata.kt]: The problem with find is that the past version is found, I don't like `getFoundCoverOfTag` (what is this even lol?)
I guess just stay with read.

File: src/sp/it/pl/audio/Item.kt (hunk 4 above)
[the remark this answers is not in the document]
Comment (Xerus2000) [reply src/sp/it/pl/audio/Item.kt]: but Try swallows the exception as well?

File: src/sp/it/pl/audio/tagging/Metadata.kt (hunk 2 above)
Comment (sghpjuikit) [reply src/sp/it/pl/audio/tagging/Metadata.kt]: getFoundCoverOfTag would become readCoverOfTag or readCoverFromTag so `find` is not wrong to use

File: src/sp/it/pl/audio/playlist/PlaylistItem.kt (hunk 5 above)
[the remark this answers is not in the document]
Comment (sghpjuikit) [reply src/sp/it/pl/audio/playlist/PlaylistItem.kt]: Indeed, but lets leave that up to new PR which will be for updating kotlin only. There is more things that will be involved with that. And I'll work on it during the weekend.

File: src/sp/it/pl/audio/Item.kt (hunk 4 above)
[the remark this answers is not in the document]
Comment (sghpjuikit) [reply src/sp/it/pl/audio/Item.kt]: Try reports error, type of which depends on the design, in this case Try<URL,Exception>. But that will be solved in next PR, there is indeed some head-scratching around this.

File: src/sp/it/pl/audio/tagging/Metadata.kt (hunk 2 above)
Comment (Xerus2000) [reply src/sp/it/pl/audio/tagging/Metadata.kt]: I much prefer `from` over `of`

**Comment by Xerus2000** [comment]
By the way, please put the `Fix #...` in the description, not the name of the PR. A commit message subject line shouldn't relate to a GitHub issue, but describe what the commit does, same for a PR.

**Comment by sghpjuikit** [comment]
It is my understanding that this way the issue gets closed automatically upon merge. So I will continue to insert the issue number in the message, but expand it to better reflect what was being done.

File: src/sp/it/pl/audio/tagging/Metadata.kt (hunk 2 above)
Comment (sghpjuikit) [reply src/sp/it/pl/audio/tagging/Metadata.kt]: Renamed to 
- readCoverFromTag
- readCoverFromDir
- readArtworkFromTag

**Comment by Xerus2000** [comment]
Inserting it in the PR description is enough, but having it at them bottom of the commit message is also fine for future reference. However, it should not be the header anywhere.

**Comment by sghpjuikit** [comment]
Noted
